development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://ikxjjsrqiuvdom:ee7b0b0d383221aeb92f9014788c761e4f4ed0e92e5994f5c5a6af00bb9bd21c@ec2-54-225-100-12.compute-1.amazonaws.com:5432/dcjgaf0nlmrup7
  channel_prefix: cf_project_production
